Task/ctaa 1435 whats new
austrianredcross/stopp-corona-ios pull request #53
Opened 2020-06-04 07:25 UTC by nilsgrabenhorst

Ticket: https://tasks.pxp-x.com/browse/CTAA-1424

2020-06-05 07:40 UTC, finnsch requested changes

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/AppVersion.swift
> +        return infoDictionary?["CFBundleShortVersionString"] as? String
```suggestion
        infoDictionary?["CFBundleShortVersionString"] as? String
```

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/AppVersion.swift
> +        return infoDictionary?["CFBundleVersion"] as? String
```suggestion
        infoDictionary?["CFBundleVersion"] as? String
```

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/WhatsNewCoordinator.swift
> +//        controller.viewModel = SavedIDsViewModel(self)
Do you intend to uncomment this code line later on?

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/WhatsNewRepository.swift
> +var appVersionHistory: AppVersionHistory = [
I would recommend to scope these two properties.

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/WhatsNewRepository.swift
> +            // using a very old versuon number in order to show what's new for 2.0:
```suggestion
            // using a very old version number in order to show what's new for 2.0:
```

2020-06-05 07:40 UTC, finnsch commented on CoronaContact/Scenes/What's New/WhatsNewViewController.swift
> +    weak var coordinator: WhatsNewCoordinator?
View controllers should not talk directly to coordinators. This has been handled by the view model so far.

2020-06-05 08:18 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/AppVersion.swift
> +        return infoDictionary?["CFBundleShortVersionString"] as? String
Fixed

2020-06-05 08:19 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/AppVersion.swift
> +        return infoDictionary?["CFBundleVersion"] as? String
Fixed

2020-06-05 08:19 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/WhatsNewCoordinator.swift
> +//        controller.viewModel = SavedIDsViewModel(self)
No, sorry, that was a leftover that I forgot to remove. Fixed.

2020-06-05 08:20 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/WhatsNewRepository.swift
> +            // using a very old versuon number in order to show what's new for 2.0:
Fixed

2020-06-07 18:43 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/WhatsNewViewController.swift
> +    weak var coordinator: WhatsNewCoordinator?
Sorry about that. I had read the Coordinator Chapter in the objc.io Architecture Book the night before, which sent me on a different path.

2020-06-07 18:43 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/WhatsNewViewController.swift
> +    weak var coordinator: WhatsNewCoordinator?
Should be fixed now.

2020-06-07 20:14 UTC, nilsgrabenhorst commented on CoronaContact/Scenes/What's New/WhatsNewRepository.swift
> +var appVersionHistory: AppVersionHistory = [
Done

2020-06-08 07:09 UTC, finnsch approved these changes

2020-06-08 07:45 UTC, merged