CTAA-1389: Risk calculation
austrianredcross/stopp-corona-ios pull request #72
Opened 2020-06-11 10:18 UTC by finnsch

2020-06-11 11:19 UTC, bastianh commented on CoronaContact/Extensions/ENIntervalNumber+date.swift
> +}
können wir das bitte aufsplitten ? ;)
```
extension ENIntervalNumber {
    var timeInterval: TimeInterval {
        Double(self) * 60 * 10
    }

    var date: Date {
        Date(timeIntervalSince1970: timeInterval)
    }
}

2020-06-11 11:27 UTC, finnsch commented on CoronaContact/Extensions/ENIntervalNumber+date.swift
> +}
Fixed :)

2020-06-11 11:38 UTC, nilsgrabenhorst requested changes

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+lastExposureDate.swift
> +        Calendar.current.date(byAdding: .day, value: daysSinceLastExposure, to: Date())
is `daysSinceLastExposure` a negative value? Otherwise the lastExposureDate is in the future, isn't it?

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENIntervalNumber+date.swift
> +}
The idiomatic way in swift is to add an initialiser to `Date` instead:
```
extension Date {
    init(_ enIntervalNumber: ENIntervalNumber) {
        self.init(timeIntervalSince1970: Double(enIntervalNumber) * 60 * 10)
    }
}
```

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/DetectDailyExposuresOperation.swift
> +            }
It would be nicer if the closure had a single `Result` argument.

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/DetectExposuresOperation.swift
> +    let exposureManager: ExposureManager
Could this be `private`?

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/DetectDailyExposuresOperation.swift
> +    let exposureManager: ExposureManager
`private`?

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/RiskCalculationController.swift
> +    private let log = ContextLogger(context: .riskCalculation)
For some reason I get a compiler error here that can be solved by being more explicit:
```suggestion
    private let log = ContextLogger(context: LoggingContext.riskCalculation)
```

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/RiskCalculationController.swift
> +    private func processDailyBatches(_ batches: [UnzippedBatch], startingFrom date: Date) {
`startingFrom` suggests moving forward in time. The second filter suggests that the algorithm actually moves backwards in time. If that's intended I would recommend renaming the argument to this:
`private func processDailyBatches(_ batches: [UnzippedBatch], before date: Date)`

Otherwise double-check the filter.

2020-06-11 11:38 UTC, nilsgrabenhorst commented on CoronaContact/Model/ExposureConfiguration.swift
> +    }
I'd prefer a convenience initialiser on `ENExposureConfiguration`

2020-06-11 16:23 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+lastExposureDate.swift
> +        Calendar.current.date(byAdding: .day, value: daysSinceLastExposure, to: Date())
Now fixed, thanks

2020-06-11 16:25 UTC, nilsgrabenhorst commented on CoronaContact/Logic/RiskCalculation/DetectExposuresOperation.swift
> +    let exposureManager: ExposureManager
Thanks for fixing.

2020-06-15 07:31 UTC, finnsch commented on CoronaContact/Logic/RiskCalculation/DetectDailyExposuresOperation.swift
> +            }
Fixed

2020-06-15 07:31 UTC, finnsch commented on CoronaContact/Logic/RiskCalculation/DetectDailyExposuresOperation.swift
> +    let exposureManager: ExposureManager
Fixed

2020-06-15 07:35 UTC, finnsch commented on CoronaContact/Logic/RiskCalculation/RiskCalculationController.swift
> +    private let log = ContextLogger(context: .riskCalculation)
Pretty strange that I didn't receive the compiler error. I added the prefix just to be sure.

2020-06-15 07:36 UTC, finnsch commented on CoronaContact/Logic/RiskCalculation/RiskCalculationController.swift
> +    private func processDailyBatches(_ batches: [UnzippedBatch], startingFrom date: Date) {
I agree with you. This makes it much clearer.

2020-06-15 07:36 UTC, finnsch commented on CoronaContact/Model/ExposureConfiguration.swift
> +    }
Good idea, fixed. :)

2020-06-15 07:38 UTC, finnsch commented on CoronaContact/Extensions/ENIntervalNumber+date.swift
> +}
I am not sure if I am a fan of this. How important is this change for you?

2020-06-15 08:58 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENIntervalNumber+date.swift
> +}
Not very important. Just pointing this out. The Standard Library & Foundation mostly use the initialiser pattern, but not always. The exception to the rule that I always trip over is converting String to Data...

2020-06-15 16:19 UTC, uluckas commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +    mutating func unique() -> UniqueAttenuationLevelValues? {
I suggest morking on a copy instead of mutating

2020-06-15 16:23 UTC, bastianh approved these changes

2020-06-15 16:31 UTC, finnsch commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +    mutating func unique() -> UniqueAttenuationLevelValues? {
Good idea, I changed the code accordingly. 👍

2020-06-15 17:02 UTC, nilsgrabenhorst requested changes

2020-06-15 17:02 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +    }
This method does something else than what the name suggests. It also destroys the value by mutating it, which is not what I would expect. I'd suggest:
* make the method non-mutating
* brainstorm on the method name

```
private extension Set where Element == ENRiskLevelValue {
    func makeUniqueAttenuationValues() -> UniqueAttenuationLevelValues? {
        
        var values = self
        
        values.remove(0)

        guard let maxValue = values.max(), let minValue = values.min() else {
            return nil
        }

        values.remove(maxValue)
        values.remove(minValue)

        guard let medianValue = values.first else {
            return nil
        }

        return UniqueAttenuationLevelValues(max: maxValue, min: minValue, median: medianValue)
    }
}
```

2020-06-15 17:02 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +        let detectionInterval: UInt = 300
You can also write 
```suggestion
        let detectionInterval: UInt = 5 * 60
```
The compiler will create a constant for you.

2020-06-15 17:02 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +        }
Are there only three values (excluding 0)?

2020-06-15 17:02 UTC, nilsgrabenhorst commented on CoronaContact/Services/RiskCalculation/RiskCalculationController.swift
> +            operation.handleDailyExposure = { [weak self] in self?.storeDailyExposure($0, at: $1) }
```suggestion
            operation.handleDailyExposure = { [weak self] (exposure, date) in self?.storeDailyExposure(exposure, at: date) }
```

2020-06-15 17:06 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +        var copy = Set(self)
`self` is already a Set.

2020-06-15 17:14 UTC, finnsch commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +        }
Yes, Uli has confirmed this. The current approach is rather fragile. Ideally the backend should return only these values as part of the exposure configuration, but this will probably take some time to implement.

2020-06-15 17:21 UTC, nilsgrabenhorst commented on CoronaContact/Extensions/ENExposureDetectionSummary+totalRiskScore.swift
> +        }
Maybe add a comment for the casual consumer of this codebase?

2020-06-15 17:23 UTC, nilsgrabenhorst approved these changes

2020-06-15 17:24 UTC, merged